#!/sbin/sh

setprop service.adb.root 1
if [ -e /sbin/bootrec-device ]
then
  /sbin/bootrec-device
fi

if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then
  rm /cache/recovery/boot

  stop tad
  stop ta_qmi_service
  stop rmt_storage

  mount -o remount,rw rootfs /
  umount -l /system
  umount -l /data
  umount -l /cache
  umount -l /storage/sdcard0
  rm -r /storage/sdcard0
  rm -r /mnt/sdcard
  rm -r /sdcard
  mkdir /sdcard
  mkdir /tmp
  rm /etc
  mkdir /etc
  cp /recovery.fstab /etc/recovery.fstab
  mount /dev/block/mmcblk0p15 /sdcard
  /sbin/recovery&
fi

#continue booting
